//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.27 at 09:09:37 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://entity.tkhts.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tkhts.entity;
