//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.28 at 03:18:16 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/tkhts/webservices/getUserServices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tkhts.webservices.getuserservices;
